name: otter-env
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.11.0
    - pip
    - altair>=5.4.1
    - ipykernel
    - jupyter_client
    - nb_conda_kernels
    - openpyxl>=3.1.5
    - otter-grader>=5.5.0
    - pandas=2.2.*
    - pytest